services:
  - type: web
    name: which-movies
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: MOVIE_DB_KEY
        sync: false
      - key: NODE_ENV
        value: production
